// duoduo reconstruction — subsystem: 10-runtime-host
// symbol: resolveRuntimePaths  (minified: Jut, daemon.pretty.js:66093)
// NOTE: readable extract from daemon.recon.js; references other top-level
// symbols. The runnable artifact is recon/daemon.recon.js (provably equivalent).

function resolveRuntimePaths(e = {}, t = process.env) {
    let n = e.homeDir ?? t.ALADUO_HOME ?? Hut.homedir(),
        r = e.runtimeDir ?? t.ALADUO_RUNTIME_DIR ?? kt.join(n, ".aladuo"),
        i = e.kernelDir ?? t.ALADUO_KERNEL_DIR ?? kt.join(n, "aladuo"),
        o = e.workDir ?? t.ALADUO_WORK_DIR ?? process.cwd(),
        s = e.bootstrapDir ?? t.ALADUO_BOOTSTRAP_DIR ?? kt.join(rve, "bootstrap"),
        a = kt.join(i, "config"),
        u = kt.join(r, "var"),
        l = kt.join(r, "run"),
        c = kt.join(u, "events"),
        d = kt.join(c, "index"),
        f = kt.join(u, "registry"),
        p = kt.join(u, "outbox"),
        m = kt.join(u, "generated"),
        h = kt.join(u, "sessions"),
        g = kt.join(u, "jobs"),
        y = kt.join(u, "channels"),
        v = kt.join(u, "ingress"),
        b = kt.join(u, "telemetry"),
        _ = kt.join(u, "usage"),
        I = kt.join(f, "sessions"),
        E = kt.join(i, "memory"),
        R = kt.join(E, "entities"),
        x = kt.join(E, "topics"),
        S = kt.join(E, "fragments"),
        D = kt.join(E, "state"),
        A = kt.join(E, "CLAUDE.md"),
        C = kt.join(u, "cadence"),
        $ = kt.join(i, "subconscious"),
        j = kt.join(u, "subconscious"),
        k = kt.join($, "playlist.md"),
        L = kt.join(u, "meta"),
        B = kt.join(L, "partitions"),
        G = kt.join(l, "locks"),
        ce = kt.join(l, "queue_offsets"),
        J = e.daemonSocketPath ?? t.ALADUO_DAEMON_SOCKET ?? kt.join(l, "daemon.sock");
    if (!kt.isAbsolute(J)) throw new Error(`daemon socket path must be absolute (the daemon and CLI clients resolve it from different working directories): ${J}. Set ALADUO_DAEMON_SOCKET (or ALADUO_RUNTIME_DIR) to an absolute path.`);
    let ee = kt.join(l, "daemon.stdout.log"),
        le = kt.join(l, "daemon.stderr.log"),
        M = kt.join(s, "meta-prompt.md"),
        ue = kt.join(n, ".claude", "CLAUDE.md"),
        $e = kt.join(rve, "bin", "duoduo");
    return {
        homeDir: n,
        runtimeDir: r,
        kernelDir: i,
        workDir: o,
        bootstrapDir: s,
        channelConfigDir: a,
        varDir: u,
        runDir: l,
        eventsDir: c,
        eventsIndexDir: d,
        registryDir: f,
        outboxDir: p,
        generatedDir: m,
        sessionsDir: h,
        jobsDir: g,
        channelsDir: y,
        varIngressDir: v,
        telemetryDir: b,
        usageDir: _,
        registrySessionsDir: I,
        memoryDir: E,
        memoryEntitiesDir: R,
        memoryTopicsDir: x,
        memoryFragmentsDir: S,
        memoryStateDir: D,
        memoryBroadcastPath: A,
        cadenceDir: C,
        subconsciousDir: $,
        subconsciousVarDir: j,
        subconsciousPlaylistPath: k,
        partitionStateDir: B,
        runLocksDir: G,
        runQueueOffsetsDir: ce,
        daemonSocketPath: J,
        daemonStdoutLogPath: ee,
        daemonStderrLogPath: le,
        metaPromptSrcPath: M,
        metaPromptDstPath: ue,
        cliEntryPath: $e
    }
}
