// duoduo reconstruction — subsystem: 10-runtime-host
// symbol: resolveRuntimePaths  (minified: GWe, daemon.pretty.js:42185)
// NOTE: readable extract from daemon.recon.js; references other top-level
// symbols. The runnable artifact is recon/daemon.recon.js (provably equivalent).

function resolveRuntimePaths(e = {}, t = process.env) {
 let n = e.homeDir ?? t.ALADUO_HOME ?? ZWe.homedir(),
  r = e.runtimeDir ?? t.ALADUO_RUNTIME_DIR ?? at.join(n, ".aladuo"),
  i = e.kernelDir ?? t.ALADUO_KERNEL_DIR ?? at.join(n, "aladuo"),
  o = e.workDir ?? t.ALADUO_WORK_DIR ?? process.cwd(),
  s = e.bootstrapDir ?? t.ALADUO_BOOTSTRAP_DIR ?? at.join(JWe, "bootstrap"),
  a = e.managedSettingsPath ?? "/etc/claude-code/settings.json",
  c = at.join(i, "config"),
  u = at.join(r, "var"),
  l = at.join(r, "run"),
  d = at.join(u, "events"),
  p = at.join(d, "index"),
  f = at.join(u, "registry"),
  m = at.join(u, "outbox"),
  h = at.join(u, "generated"),
  g = at.join(u, "sessions"),
  v = at.join(u, "jobs"),
  S = at.join(u, "channels"),
  _ = at.join(u, "ingress"),
  b = at.join(u, "telemetry"),
  w = at.join(u, "usage"),
  x = at.join(f, "sessions"),
  R = at.join(i, "memory"),
  T = at.join(R, "entities"),
  P = at.join(R, "topics"),
  E = at.join(R, "fragments"),
  O = at.join(R, "state"),
  A = at.join(R, "CLAUDE.md"),
  D = at.join(O, "meta-memory-state.json"),
  H = at.join(u, "cadence"),
  K = at.join(H, "inbox"),
  te = at.join(H, "queue.md"),
  z = at.join(i, "subconscious"),
  xe = at.join(u, "subconscious"),
  Ne = at.join(z, "playlist.md"),
  ve = at.join(u, "meta"),
  Tt = at.join(ve, "partitions"),
  Ht = at.join(l, "locks"),
  _e = at.join(l, "queue_offsets"),
  Ze = at.join(l, "spine.sock"),
  ae = at.join(l, "daemon.stdout.log"),
  C = at.join(l, "daemon.stderr.log"),
  L = at.join(s, "meta-prompt.md"),
  ne = at.join(n, ".claude", "CLAUDE.md");
 return {
  homeDir: n,
  runtimeDir: r,
  kernelDir: i,
  workDir: o,
  bootstrapDir: s,
  channelConfigDir: c,
  varDir: u,
  runDir: l,
  eventsDir: d,
  eventsIndexDir: p,
  registryDir: f,
  outboxDir: m,
  generatedDir: h,
  sessionsDir: g,
  jobsDir: v,
  channelsDir: S,
  varIngressDir: _,
  telemetryDir: b,
  usageDir: w,
  registrySessionsDir: x,
  memoryDir: R,
  memoryEntitiesDir: T,
  memoryTopicsDir: P,
  memoryFragmentsDir: E,
  memoryStateDir: O,
  memoryBroadcastPath: A,
  memoryMetaStatePath: D,
  cadenceDir: H,
  cadenceInboxDir: K,
  cadenceQueuePath: te,
  subconsciousDir: z,
  subconsciousVarDir: xe,
  subconsciousPlaylistPath: Ne,
  partitionStateDir: Tt,
  runLocksDir: Ht,
  runQueueOffsetsDir: _e,
  spineSocketPath: Ze,
  daemonStdoutLogPath: ae,
  daemonStderrLogPath: C,
  metaPromptSrcPath: L,
  metaPromptDstPath: ne,
  managedSettingsPath: a
 }
}
