// duoduo reconstruction — subsystem: 10-runtime-host
// symbol: resolveRuntimePaths  (minified: R7e, daemon.pretty.js:56837)
// NOTE: readable extract from daemon.recon.js; references other top-level
// symbols. The runnable artifact is recon/daemon.recon.js (provably equivalent).

function resolveRuntimePaths(e = {}, t = process.env) {
    let n = e.homeDir ?? t.ALADUO_HOME ?? k7e.homedir(),
        r = e.runtimeDir ?? t.ALADUO_RUNTIME_DIR ?? vt.join(n, ".aladuo"),
        i = e.kernelDir ?? t.ALADUO_KERNEL_DIR ?? vt.join(n, "aladuo"),
        o = e.workDir ?? t.ALADUO_WORK_DIR ?? process.cwd(),
        s = e.bootstrapDir ?? t.ALADUO_BOOTSTRAP_DIR ?? vt.join(E7e, "bootstrap"),
        a = vt.join(i, "config"),
        l = vt.join(r, "var"),
        u = vt.join(r, "run"),
        c = vt.join(l, "events"),
        d = vt.join(c, "index"),
        p = vt.join(l, "registry"),
        f = vt.join(l, "outbox"),
        m = vt.join(l, "generated"),
        h = vt.join(l, "sessions"),
        y = vt.join(l, "jobs"),
        _ = vt.join(l, "channels"),
        k = vt.join(l, "ingress"),
        v = vt.join(l, "telemetry"),
        b = vt.join(l, "usage"),
        I = vt.join(p, "sessions"),
        T = vt.join(i, "memory"),
        S = vt.join(T, "entities"),
        w = vt.join(T, "topics"),
        C = vt.join(T, "fragments"),
        O = vt.join(T, "state"),
        A = vt.join(T, "CLAUDE.md"),
        x = vt.join(O, "meta-memory-state.json"),
        P = vt.join(l, "cadence"),
        M = vt.join(P, "inbox"),
        j = vt.join(P, "queue.md"),
        H = vt.join(i, "subconscious"),
        J = vt.join(l, "subconscious"),
        ee = vt.join(H, "playlist.md"),
        ie = vt.join(l, "meta"),
        re = vt.join(ie, "partitions"),
        Ye = vt.join(u, "locks"),
        je = vt.join(u, "queue_offsets"),
        Se = e.daemonSocketPath ?? t.ALADUO_DAEMON_SOCKET ?? vt.join(u, "daemon.sock");
    if (!vt.isAbsolute(Se)) throw new Error(`daemon socket path must be absolute (the daemon and CLI clients resolve it from different working directories): ${Se}. Set ALADUO_DAEMON_SOCKET (or ALADUO_RUNTIME_DIR) to an absolute path.`);
    let lt = vt.join(u, "daemon.stdout.log"),
        Fe = vt.join(u, "daemon.stderr.log"),
        qe = vt.join(s, "meta-prompt.md"),
        F = vt.join(n, ".claude", "CLAUDE.md");
    return {
        homeDir: n,
        runtimeDir: r,
        kernelDir: i,
        workDir: o,
        bootstrapDir: s,
        channelConfigDir: a,
        varDir: l,
        runDir: u,
        eventsDir: c,
        eventsIndexDir: d,
        registryDir: p,
        outboxDir: f,
        generatedDir: m,
        sessionsDir: h,
        jobsDir: y,
        channelsDir: _,
        varIngressDir: k,
        telemetryDir: v,
        usageDir: b,
        registrySessionsDir: I,
        memoryDir: T,
        memoryEntitiesDir: S,
        memoryTopicsDir: w,
        memoryFragmentsDir: C,
        memoryStateDir: O,
        memoryBroadcastPath: A,
        memoryMetaStatePath: x,
        cadenceDir: P,
        cadenceInboxDir: M,
        cadenceQueuePath: j,
        subconsciousDir: H,
        subconsciousVarDir: J,
        subconsciousPlaylistPath: ee,
        partitionStateDir: re,
        runLocksDir: Ye,
        runQueueOffsetsDir: je,
        daemonSocketPath: Se,
        daemonStdoutLogPath: lt,
        daemonStderrLogPath: Fe,
        metaPromptSrcPath: qe,
        metaPromptDstPath: F
    }
}
