// Which first-party code the docs cover, and which doc sections rest on the
// fewest symbols -- so analysis effort goes where no doc has looked yet
// instead of where someone happens to look next.
//
// Reads the generated xref/symbols maps and the hand-made subsystem map, scans
// the docs for symbol mentions (doc_cites.mjs) and writes a Markdown report:
//   1. uncited first-party symbols, per NN- subsystem directory
//   2. the `##`/`###` sections of each doc with how many distinct symbols each
//      cites, ascending (a mechanism section citing nothing is a claim with no
//      evidence attached)
//   3. the unnamed top-level declarations most used by first-party code: the
//      queue for name_symbol.mjs
// A JSON copy sits next to it for tools.
//
// Usage: node doc_coverage.mjs [--maps <dir>] [--build <OUT>] [--docs <dir>] <out.md>
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { scanDocs } from "./doc_cites.mjs";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, "..");
const argv = process.argv.slice(2);
const opt = (k, dflt) => { const i = argv.indexOf(k); if (i === -1) return dflt; const v = argv[i + 1]; argv.splice(i, 2); return v; };
const MAPS = opt("--maps", path.join(ROOT, "maps"));
const BUILD = opt("--build", null);
const DOCS = opt("--docs", path.resolve(ROOT, "..", "docs"));
const OUT = argv[0];
if (!OUT) { console.error("usage: node doc_coverage.mjs [--maps <dir>] [--build <OUT>] [--docs <dir>] <out.md>"); process.exit(2); }

const readJson = p => JSON.parse(fs.readFileSync(p, "utf8"));
const xref = readJson(path.join(BUILD ?? MAPS, "xref_daemon.json"));
const subsys = readJson(path.join(MAPS, "subsys_daemon.json"));
const docs = fs.readdirSync(DOCS).filter(f => f.endsWith(".md")).sort().map(f => path.join(DOCS, f));
const names = new Set(Object.keys(xref.symbols));
const cites = scanDocs(docs, names);

// 1. uncited per subsystem
const perDir = new Map();
for (const real of names) {
  const d = subsys[real] ?? "(none)";
  const e = perDir.get(d) ?? perDir.set(d, { total: 0, uncited: [] }).get(d);
  e.total++;
  if (!cites.has(real)) e.uncited.push(real);
}
// 2. sections: doc -> section -> Set(real)
const perSection = new Map();
for (const [real, hits] of cites) for (const h of hits) {
  const k = `${h.doc} § ${h.section}`;
  (perSection.get(k) ?? perSection.set(k, new Set()).get(k)).add(real);
}
// every section of every doc, including those citing nothing
for (const doc of docs) {
  const base = path.basename(doc);
  let inFence = false;
  for (const L of fs.readFileSync(doc, "utf8").split("\n")) {
    if (/^```/.test(L)) inFence = !inFence;
    if (!inFence && /^#{2,3} /.test(L)) { const k = `${base} § ${L.replace(/^#+ /, "").trim()}`; if (!perSection.has(k)) perSection.set(k, new Set()); }
  }
}

const cited = [...names].filter(n => cites.has(n)).length;
const lines = [];
lines.push(`# Doc coverage of the first-party daemon symbols (${xref.version})`, "");
lines.push(`Generated by \`tools/doc_coverage.mjs\` from \`xref_daemon.json\`, \`subsys_daemon.json\` and ${docs.map(d => path.basename(d)).join(", ")}. A symbol counts as cited when a doc spells its real name inside a backtick span; the build's citation checkers decide whether such a mention is valid.`, "");
lines.push(`| symbols | cited by some doc | uncited |`, `|---|---|---|`, `| ${names.size} | ${cited} | ${names.size - cited} |`, "");
lines.push(`## 1. Uncited symbols per subsystem`, "");
lines.push(`| subsystem | symbols | uncited | names |`, `|---|---|---|---|`);
for (const [d, e] of [...perDir].sort()) lines.push(`| ${d} | ${e.total} | ${e.uncited.length} | ${e.uncited.sort().join(", ")} |`);
lines.push("", `## 2. Doc sections by distinct symbols cited (ascending)`, "");
lines.push(`| section | symbols |`, `|---|---|`);
// only the docs that cite code at all: the product-manager guide and the
// comparison carry no citations by design
const perDoc = new Map();
for (const [k, s] of perSection) { const d = k.split(" § ")[0]; const set = perDoc.get(d) ?? perDoc.set(d, new Set()).get(d); for (const r of s) set.add(r); }
const citingDocs = new Set([...perDoc].filter(([, s]) => s.size >= 10).map(([d]) => d));
for (const [k, s] of [...perSection].filter(([k]) => citingDocs.has(k.split(" § ")[0])).sort((a, b) => a[1].size - b[1].size || a[0].localeCompare(b[0]))) lines.push(`| ${k.replace(/\|/g, "\\|")} | ${s.size} |`);
lines.push("", `## 3. Unnamed top-level code most used by first-party symbols`, "");
lines.push(`| short | line | kind | used by |`, `|---|---|---|---|`);
for (const [short, u] of Object.entries(xref.unnamed).slice(0, 40)) lines.push(`| ${short} | ${u.line} | ${u.kind} | ${u.usedBy.length}: ${u.usedBy.slice(0, 5).join(", ")}${u.usedBy.length > 5 ? ", …" : ""} |`);
fs.writeFileSync(OUT, lines.join("\n") + "\n");
fs.writeFileSync(OUT.replace(/\.md$/, "") + ".json", JSON.stringify({
  version: xref.version, symbols: names.size, cited, uncited: names.size - cited,
  perSubsystem: Object.fromEntries([...perDir].sort().map(([d, e]) => [d, { total: e.total, uncited: e.uncited.sort() }])),
  sections: Object.fromEntries([...perSection].sort().map(([k, s]) => [k, [...s].sort()])),
}, null, 1) + "\n");
console.log(`doc coverage: ${cited}/${names.size} symbols cited, ${names.size - cited} uncited -> ${OUT}`);
