// Compare the artifacts a rebuild.sh run just generated against the committed
// copies under reconstruction/, or (write mode) replace the committed copies.
//
// Why this exists: rebuild.sh used to prove things about $OUT only. Nothing
// compared $OUT with recon/, maps/ or first-party/, and promoting them was a
// list of manual cp steps in CLAUDE.md. So a committed recon/ could be stale,
// or hand-edited, while every check in the pipeline stayed green -- the
// equivalence proof was about a file nobody reads.
//
// Compared (fresh in $OUT -> committed under reconstruction/):
//   daemon.recon.js                        -> recon/daemon.recon.js     (bytes)
//   {rename,symbols,blocks}_<b>.json       -> maps/                     (JSON, minus machine-local paths)
//   <b>.exports.json                       -> maps/                     (bytes)
//   RENAME_TABLE.md / RENAME_TABLE_<b>.md  -> maps/                     (bytes; daemon keeps the unsuffixed name)
//   pipeline_report.json                   -> maps/                     (JSON, minus environment/verdicts)
//   first-party/**                         -> first-party/              (bytes, whole tree, both directions)
//
// Usage: node promote.mjs check|write <OUT> <reconstruction-dir> <bundle...>
// check exits 1 if anything differs and prints what; write copies and exits 0.
import fs from "node:fs";
import path from "node:path";

const [MODE, OUT, ROOT, ...BUNDLES] = process.argv.slice(2);
if (!["check", "write"].includes(MODE) || !OUT || !ROOT || !BUNDLES.length) {
  console.error("usage: node promote.mjs check|write <OUT> <reconstruction-dir> <bundle...>");
  process.exit(2);
}

// fields that legitimately differ between machines or runs
const LOCAL = new Set(["source", "input", "out", "environment", "verdicts"]);
const strip = v => Array.isArray(v) ? v.map(strip)
  : v && typeof v === "object" ? Object.fromEntries(Object.entries(v).filter(([k]) => !LOCAL.has(k)).map(([k, x]) => [k, strip(x)]))
  : v;
const sameJson = (a, b) => JSON.stringify(strip(JSON.parse(fs.readFileSync(a, "utf8")))) === JSON.stringify(strip(JSON.parse(fs.readFileSync(b, "utf8"))));
const sameBytes = (a, b) => fs.readFileSync(a).equals(fs.readFileSync(b));

const pairs = []; // [fresh, committed, kind]
if (BUNDLES.includes("daemon")) pairs.push([`${OUT}/daemon.recon.js`, `${ROOT}/recon/daemon.recon.js`, "bytes"]);
for (const b of BUNDLES) {
  for (const k of ["rename", "symbols", "blocks"]) pairs.push([`${OUT}/${k}_${b}.json`, `${ROOT}/maps/${k}_${b}.json`, "json"]);
  pairs.push([`${OUT}/${b}.exports.json`, `${ROOT}/maps/${b}.exports.json`, "bytes"]);
}
const table = b => (b === "daemon" ? "RENAME_TABLE.md" : `RENAME_TABLE_${b}.md`);
for (const b of BUNDLES) pairs.push([`${OUT}/${table(b)}`, `${ROOT}/maps/${table(b)}`, "bytes"]);
pairs.push([`${OUT}/pipeline_report.json`, `${ROOT}/maps/pipeline_report.json`, "json"]);

const walk = d => fs.existsSync(d) ? fs.readdirSync(d, { recursive: true }).filter(f => fs.statSync(path.join(d, f)).isFile()).sort() : [];
const freshFp = `${OUT}/first-party`, committedFp = `${ROOT}/first-party`;
const fpFiles = new Set([...walk(freshFp), ...walk(committedFp)]);
for (const f of fpFiles) pairs.push([path.join(freshFp, f), path.join(committedFp, f), "bytes"]);

const diffs = [];
for (const [fresh, committed, kind] of pairs) {
  const rel = path.relative(ROOT, committed);
  if (!fs.existsSync(fresh)) { diffs.push({ rel, what: "not generated by this run", fresh, committed, remove: true }); continue; }
  if (!fs.existsSync(committed)) { diffs.push({ rel, what: "new (not committed)", fresh, committed }); continue; }
  const same = kind === "json" ? sameJson(fresh, committed) : sameBytes(fresh, committed);
  if (!same) diffs.push({ rel, what: "differs", fresh, committed });
}

if (MODE === "write") {
  for (const d of diffs) {
    if (d.remove) { if (d.rel.startsWith("first-party")) fs.rmSync(d.committed); continue; }
    fs.mkdirSync(path.dirname(d.committed), { recursive: true });
    fs.copyFileSync(d.fresh, d.committed);
  }
  // prune directories the new tree no longer has
  for (const d of fs.existsSync(committedFp) ? fs.readdirSync(committedFp) : []) {
    const p = path.join(committedFp, d);
    if (fs.statSync(p).isDirectory() && fs.readdirSync(p).length === 0) fs.rmdirSync(p);
  }
  console.error(`  promoted ${diffs.length} changed artifact(s) into ${ROOT}`);
  for (const d of diffs.slice(0, 30)) console.error(`    ${d.remove ? "removed" : "wrote"}  ${d.rel}`);
  process.exit(0);
}

console.error(`  committed artifacts: ${pairs.length} compared, ${diffs.length} differ from this run`);
for (const d of diffs.slice(0, 30)) console.error(`    ${d.what.padEnd(26)} ${d.rel}`);
if (diffs.length > 30) console.error(`    ... and ${diffs.length - 30} more`);
process.exit(diffs.length ? 1 : 0);
